GET http://localhost:5062/games 

###
GET http://localhost:5062/games/3

###
POST http://localhost:5062/games
Content-Type: application/json

{
    "name": "Test Game",
    "genreId": "3",
    "price": 59.99,
    "releaseDate": "2005-05-17"
}

###
PUT http://localhost:5062/games/2
Content-Type: application/json 

{
    "name": "Lego Star Wars III",
    "genreId": "3",
    "price": 9.99,
    "releaseDate": "2005-05-17"
}

###
DELETE http://localhost:5062/games/3

###
GET http://localhost:5062/genres